[app]
host = "127.0.0.1"
port = 23562
recaptcha_secret = "" # 填写recaptcha私钥(没有的话可以自己申请一个，需要和前端src/views/Viewer和DanmakuSearch.vue里的设定值对应)
allow_origin_list = ['luetrim.top', 'lue-trim.github.io'] # 访问/views时限制访问来源用的
blrec_url = "http://127.0.0.1:2233"
allow_post_ips = ['127.0.0.1'] # 只有列表里的IP地址可以发送post请求

[subtitle]
check_interval = 43200 # 自动检查间隔，单位为s
[[subtitle.config]] # 可以填写多个
uid = 1950658 # B站UID
sid = 210077 # 录播所在合集的season_id(可以从浏览器地址栏获取)
max_videos = 10 # 最大尝试匹配视频数(即只有合集的前n个视频会被自动匹配)

[postgres]
host = "127.0.0.1"
port = 63154
user = "postgres" # postgres用户名，保持默认即可
password = "" # postgres密码
database = "matsuri_db" # 要加载的数据库名称（如果不存在，要先创建一个）

[log]
file = ""
level = "INFO"
